[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python3 -m venv --copies /opt/venv",
    "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT --log-level info" 