[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
    "python3 -m venv --copies /opt/venv",
    "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && python3 app.py" 